export const SHOWCASE_POSTER_CARD_WIDTH = 148
export const SHOWCASE_POSTER_IMAGE_HEIGHT = 222
export const SHOWCASE_POSTER_TITLE_BLOCK_HEIGHT = 24
export const SHOWCASE_POSTER_ITEM_OUTER_HEIGHT =
  SHOWCASE_POSTER_IMAGE_HEIGHT + SHOWCASE_POSTER_TITLE_BLOCK_HEIGHT
export const SHOWCASE_POSTER_MIN_COLUMN_GAP = 24
export const SHOWCASE_POSTER_ROW_GAP = 40
